### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by suntrop** [orefalo/LLM_Superset.popclipext#2]
Why is it limited to just a couple of languages?

**Comment by orefalo** [comment]
its not

the real limit is the LLM supported languages.  
 I started with a small list, feel free to create a pull req and add more. it's trivial to do, check Config.json

which languages would you be interested in?

**Comment by orefalo** [comment]
Problem fixed - added gpt-01 models and more languages along with other improvements

let me know,
closing for now
